### ISSUE TITLE
SS soldier spawn BFG facility

### ISSUE THREAD

**Issue by Fa3242** [0Eagle/Nightmarerus#1]
I'm trying to play your maps with a friend but after a while, in MAP04 the starting area get flooded by SS soldier and it becomes impossible. Is there a way to avoid it?
The map is awesome by the way! Keep up the good work ;)

**Comment by 0Eagle** [comment]
don't use resurrect in the console.

**Comment by Fa3242** [comment]
I guessed it was that... Does it mean you can only have 1 life? I did not use resurrect but had multiple life, so I guess the game calls "resurrects" when you die.
You must play with 1 life right?
Thank you!

**Comment by 0Eagle** [comment]
each restart of the map with the preservation of things complicates the passage.
